# Generated by Django 5.2.1 on 2025-11-04 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("interns", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stipend",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("month", models.CharField(max_length=7)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("working_days", models.PositiveIntegerField()),
                ("leaves_taken", models.PositiveIntegerField()),
                ("comments", models.TextField(blank=True)),
                (
                    "intern_approval",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                        ],
                        default="Pending",
                        max_length=10,
                    ),
                ),
                (
                    "hr_approval",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                        ],
                        default="Pending",
                        max_length=10,
                    ),
                ),
                (
                    "hod_approval",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                        ],
                        default="Pending",
                        max_length=10,
                    ),
                ),
                ("invoice_url", models.URLField(blank=True)),
                ("intern_signature_url", models.TextField(blank=True)),
                ("hr_signature_url", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "intern",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stipends",
                        to="interns.intern",
                    ),
                ),
            ],
            options={
                "unique_together": {("intern", "month")},
            },
        ),
    ]
