# Generated by Django 5.2.1 on 2025-11-04 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                (
                    "resume",
                    models.FileField(blank=True, null=True, upload_to="resumes/"),
                ),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="photos/"),
                ),
                (
                    "signature",
                    models.ImageField(blank=True, null=True, upload_to="signatures/"),
                ),
                (
                    "last_project_report",
                    models.FileField(
                        blank=True, null=True, upload_to="project_reports/"
                    ),
                ),
                ("quest_data", models.JSONField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending Mentor Assignment", "Pending Mentor Assignment"),
                            (
                                "Pending Interview Assessment",
                                "Pending Interview Assessment",
                            ),
                            ("Pending HOD Approval", "Pending HOD Approval"),
                            ("Rejected", "Rejected"),
                            ("Selected", "Selected"),
                            ("Onboarded", "Onboarded"),
                        ],
                        default="Pending Mentor Assignment",
                        max_length=50,
                    ),
                ),
                ("interview_feedback", models.JSONField(blank=True, null=True)),
                ("hod_feedback", models.TextField(blank=True, null=True)),
                ("joining_date", models.DateField(blank=True, null=True)),
                ("joining_time", models.TimeField(blank=True, null=True)),
                (
                    "joining_location",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
