# Generated by Django 5.2.1 on 2025-11-04 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("Web Development", "Web Development"),
                            ("SAP BTP Development", "SAP BTP Development"),
                            ("RPA", "RPA"),
                            ("Gen AI & LLM", "Gen AI & LLM"),
                            ("IIoT Development", "IIoT Development"),
                            ("IIoT Field", "IIoT Field"),
                            ("SCM", "SCM"),
                            ("Project Management", "Project Management"),
                        ],
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
