# Generated by Django 5.2.1 on 2025-11-04 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("exits", "0001_initial"),
        ("interns", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="exitrequest",
            name="intern",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exit_requests",
                to="interns.intern",
            ),
        ),
    ]
