# Generated by Django 5.2.1 on 2025-11-04 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("candidates", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Intern",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("joining_date", models.DateField()),
                (
                    "offer_letter",
                    models.FileField(blank=True, null=True, upload_to="offer_letters/"),
                ),
                ("bank_details", models.JSONField(blank=True, null=True)),
                ("extension_allowed", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Completed", "Completed"),
                            ("Left", "Left"),
                        ],
                        default="Active",
                        max_length=20,
                    ),
                ),
                (
                    "aadhar_card",
                    models.FileField(
                        blank=True, null=True, upload_to="intern_documents/aadhar/"
                    ),
                ),
                (
                    "pan_card",
                    models.FileField(
                        blank=True, null=True, upload_to="intern_documents/pan/"
                    ),
                ),
                (
                    "bank_passbook",
                    models.FileField(
                        blank=True, null=True, upload_to="intern_documents/bank/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "candidate",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intern_profile",
                        to="candidates.candidate",
                    ),
                ),
            ],
        ),
    ]
