# Generated by Django 5.2.1 on 2025-11-18 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interns", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="intern",
            name="noc",
            field=models.FileField(
                blank=True, null=True, upload_to="intern_documents/noc/"
            ),
        ),
    ]
