# Generated by Django 5.2.1 on 2025-11-04 06:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("extensions", "0001_initial"),
        ("interns", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="extensionpermission",
            name="hod_approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hod_extension_approvals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="extensionpermission",
            name="hr_approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hr_extension_approvals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="extensionpermission",
            name="intern",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="extension_permission",
                to="interns.intern",
            ),
        ),
        migrations.AddField(
            model_name="extensionrequest",
            name="intern",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="extension_requests",
                to="interns.intern",
            ),
        ),
    ]
