# Generated by Django 5.2.1 on 2025-11-12 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extensions", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="extensionrequest",
            name="hod_comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="extensionrequest",
            name="hr_comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="extensionrequest",
            name="mentor_comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="extensionrequest",
            name="mhr_approval",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                ],
                default="Pending",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="extensionrequest",
            name="mhr_comments",
            field=models.TextField(blank=True),
        ),
    ]
