# Generated by Django 5.2.1 on 2025-11-07 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webhooks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sync_type",
                    models.CharField(
                        choices=[
                            ("FULL", "Full Sync"),
                            ("INCREMENTAL", "Incremental Sync"),
                            ("MANUAL", "Manual Sync"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(default="RUNNING", max_length=20)),
                ("records_fetched", models.IntegerField(default=0)),
                ("records_saved", models.IntegerField(default=0)),
                ("records_updated", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("last_sync_timestamp", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-start_time"],
            },
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="branch",
            field=models.CharField(
                help_text="e.g., Mechanical Engineering", max_length=100
            ),
        ),
        migrations.CreateModel(
            name="JotFormCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "jotform_submission_id",
                    models.CharField(max_length=255, unique=True),
                ),
                ("jotform_id", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("date_of_birth", models.CharField(blank=True, max_length=50)),
                ("gender", models.CharField(blank=True, max_length=20)),
                ("address", models.TextField(blank=True)),
                ("unique_id", models.CharField(blank=True, max_length=100)),
                ("college_name", models.CharField(blank=True, max_length=255)),
                ("qualification", models.CharField(blank=True, max_length=100)),
                ("branch", models.CharField(blank=True, max_length=100)),
                ("year_of_passing", models.CharField(blank=True, max_length=50)),
                ("semester", models.CharField(blank=True, max_length=20)),
                ("area_of_interest", models.CharField(blank=True, max_length=255)),
                ("preferred_location", models.CharField(blank=True, max_length=255)),
                ("linkedin_profile", models.URLField(blank=True, max_length=500)),
                ("reference_by", models.CharField(blank=True, max_length=255)),
                ("tnp_contact", models.TextField(blank=True)),
                ("applicant_status", models.CharField(blank=True, max_length=50)),
                ("available_6_months", models.CharField(blank=True, max_length=10)),
                ("willing_plant_location", models.CharField(blank=True, max_length=10)),
                ("willing_shifts", models.CharField(blank=True, max_length=10)),
                ("cv_url", models.URLField(blank=True, max_length=500, null=True)),
                ("photo", models.URLField(blank=True, max_length=500, null=True)),
                ("signature", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "last_project_report",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                ("has_cv", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        default="Pending Mentor Assignment", max_length=50
                    ),
                ),
                ("submission_date", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source", models.CharField(default="JotForm", max_length=20)),
                (
                    "assigned_mentor",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "assigned_mentor_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("interview_feedback", models.JSONField(blank=True, null=True)),
                ("hod_feedback", models.TextField(blank=True, null=True)),
                ("department", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "departmentName",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "ordering": ["-submission_date"],
                "indexes": [
                    models.Index(
                        fields=["jotform_submission_id"],
                        name="webhooks_jo_jotform_3d7a9c_idx",
                    ),
                    models.Index(
                        fields=["submission_date"],
                        name="webhooks_jo_submiss_eeda4c_idx",
                    ),
                ],
            },
        ),
    ]
